### ISSUE TITLE
PyWavelets package addition request

### ISSUE THREAD

**Issue by d-dimos** [a3d3-institute/HDRchallenge#8]
Hello,

Could you please add the PyWavelets package in the requirements?

Thank you in advance.

**Comment by ytchoutw** [comment]
Fixed in https://github.com/a3d3-institute/HDRchallenge/pull/11
You can now use this package. Please check the example here  https://github.com/a3d3-institute/HDRchallenge/tree/main/scripts/example_submissions/with_requirements
