### ISSUE TITLE
List of "Anomalies (Not Detectable with Match-Filtering Pipeline)"

### ISSUE THREAD

**Issue by dbkeitel** [a3d3-institute/HDRchallenge#9]
Dear challenge maintainers, as co-chairs of the continuous waves working group of the LIGO-Virgo-KAGRA collaboration we noticed your postings and are happy for our kind of science targets to be mentioned, but feel the need to point out that listing them as “Anomalies (Not Detectable with Match-Filtering Pipeline)“ on https://www.codabench.org/competitions/2626/ (as the point “2. Continuous Waves from Spinning Neutron Stars”) is not appropriate. CWs are in fact generally considered as well-modelled sources and only computational cost limits the applicability of matched filters, but still the collaboration performs searches for known pulsars with fully-coherent matched filtering (e.g. https://doi.org/10.3847/1538-4357/ac6acf on O3 data) and also many of the state-of-the-art algorithms for computationally limited analyses (such as  all-sky searches) are based on semi-coherent combinations of matched filters over shorter periods. We request that you correct the text on that page.

(For instance, you could phrase this list of non-CBC targets as “not yet detected” rather than “not detectable” with a matched filter, since also e.g. for supernovae we might eventually arrive at a point where models are good and dense enough to use those methods after all.)

-- David Keitel, Michal Bejger, John T Whelan, Takahiro S. Yamamoto

**Comment by katyagovorkova** [comment]
Dear David, Michal, John, and Takahiro,
Thanks a lot for your feedback. You’ve made a really good point, and we’ve adjusted the text on the competition page to better reflect this. We appreciate your input and are glad to have the chance to make things more accurate for everyone involved. 
Please, let us know if there are additional concerns. 
Thanks!

**Comment by dbkeitel** [comment]
Thanks for taking care of this @katyagovorkova and I hope you get a lot of great submissions!
